[project]
name = "stake-pledge"
description = "Accountability dApp - stake STX on your commitments"
authors = []
telemetry = false
cache_dir = "./.cache"

[contracts.stake-pledge]
path = "contracts/stake-pledge.clar"
clarity_version = 3
epoch = 3.0

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
